#!/bin/sh

echo "Running tests before commit..."

cd "Assignment 4"

pytest test.py

if [ $? -ne 0 ]; then
echo "Tests failed. Commit aborted."
exit 1
fi

echo "Tests passed. Proceeding with commit."
exit 0
